[package]
name = "pyembed_downloader_gui"
version = "0.1.0"
authors = ["wzv5 <wzv5@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
tokio = "0.2.22"
log = "0.4.11"
pyembed_downloader = { path = "../pyembed_downloader" }
